name: Push docker image to packages

on: 
  push:
    branches: [ "main" ]

jobs:
  build:
      name: Build docker image and push to github packages
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Build docker image
          run: docker build --build-arg ENVIRONMENT=testing -t ghcr.io/ivarot/sagaofcards-frontend:latest .

        - name: Log in to registry
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        - name: Push image
          run: docker push ghcr.io/ivarot/sagaofcards-frontend:latest
          
        
